# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for Voooxly (menu bar app, no window).
# Build:  ~/.voooxly/venv/bin/pyinstaller Voooxly.spec

block_cipher = None

hiddenimports = [
    "pynput.keyboard._darwin",
    "pynput.mouse._darwin",
    "pynput._util.darwin",
    "rumps",
    "AppKit",
    "Quartz",
    "ApplicationServices",
    "Cocoa",
    "sounddevice",
    "webrtcvad",
    "numpy",
    "yaml",
    "requests",
    "anthropic",
    "Security",
]

datas = [
    ("config.yaml", "."),
    (".env.example", "."),
    ("assets/menubar.png", "assets"),
    ("assets/menubar@2x.png", "assets"),
    ("assets/menubar-rec.png", "assets"),
    ("assets/menubar-rec@2x.png", "assets"),
]

# embedded whisper-server + its dylibs/backends (generated by
# scripts/bundle-whisper.sh) — the recipient does not need Homebrew.
import glob as _glob

vendor_whisper = [(p, "whisper") for p in _glob.glob("vendor/whisper/*")]
if not vendor_whisper:
    raise SystemExit("vendor/whisper vacío: ejecuta scripts/bundle-whisper.sh antes del build")

a = Analysis(
    ["entry.py"],
    pathex=["src"],
    binaries=vendor_whisper,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["matplotlib", "pytest", "tkinter"],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="Voooxly",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,          # menu bar app: no console
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    name="Voooxly",
)

# .app bundle (LSUIElement for a menu bar app with no Dock icon)
app = BUNDLE(
    coll,
    name="Voooxly.app",
    icon="assets/Voooxly.icns",
    # WATCH OUT: the identifier goes as its own argument and the dict is named
    # `info_plist` (with `plist=` PyInstaller silently ignores it and the app
    # ships without NSMicrophoneUsageDescription → macOS delivers mic silence).
    # The identifier must match the signing one (TCC demands it).
    # WATCH OUT: the TCC permissions (Accessibility/Input Monitoring/Microphone)
    # hang off this identifier + the certificate. Touching it forces re-granting
    # ALL of them, so it only changes for a brand rename like the 1.0.0 one.
    bundle_identifier="com.eduardocrovetto.voooxly",
    info_plist={
        "CFBundleName": "Voooxly",
        "CFBundleDisplayName": "Voooxly",
        "CFBundleIdentifier": "com.eduardocrovetto.voooxly",
        "CFBundleVersion": "1.9.0",
        "CFBundleShortVersionString": "1.9.0",
        "LSMinimumSystemVersion": "13.0",
        "LSUIElement": True,        # menu bar app: no Dock, no main menu
        "NSMicrophoneUsageDescription": "Voooxly needs the microphone to transcribe your voice.",
        "NSSpeechRecognitionUsageDescription": "Voooxly transcribes your dictation locally.",
    },
)
